### ISSUE TITLE
items in i_pouch not stack in pile

### ISSUE THREAD

**Issue by Seokotov** [cbnolok/SphereX-Scriptpack#10] opened 2019-01-24 20:17 UTC
if you drop some ingots to pouch and try to add some more it's not stacked in a pile
problem only with this cont

i_provisions_misc.scp

[ITEMDEF 09b0]
DEFNAME=i_pouch
TYPE=t_container
//TDATA2=047
TDATA2=040
TDATA3=010001
TDATA4=0900090
DYE=1
FLIP=1
VALUE=13
WEIGHT=0.1
RESOURCES=1 i_hides_cut,1 i_thread
SKILLMAKE=Tailoring 10.0,t_sewing_kit
CATEGORY=Provisions - Miscellaneous
SUBSECTION=Containers
DESCRIPTION=Pouch
DUPELIST=0e79

looks like another cont bugged

**Comment by Jhobean** [comment] 2020-10-05 20:12
The problem is not in the script, it's in the tileDATA.

You must set layer 0 instead of layer 13
![image](https://user-images.githubusercontent.com/51728381/95127023-57040e00-0725-11eb-9f2d-e5aa68a12c17.png)



You can close this issue.

**Closed** 2020-12-16 20:16 UTC
